# Generated by Django 5.0.3 on 2024-03-27 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='name',
            new_name='user_name',
        ),
    ]
