# Generated by Django 5.0.3 on 2024-03-27 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_vendor_user_vendor_is_staff'),
        ('userauths', '0008_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vendor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.vendor'),
        ),
    ]
