# Generated by Django 5.0.3 on 2024-03-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0009_user_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vendor',
        ),
    ]
