# Generated by Django 5.0.3 on 2024-03-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vendor_date_alter_products_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='products',
            new_name='product',
        ),
    ]
