# Generated by Django 5.0.3 on 2024-03-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_products_productreview_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
